# Generated by Django 3.0.3 on 2020-09-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stockinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=20)),
                ('stock_no', models.CharField(max_length=10)),
                ('stock_lastprice', models.IntegerField(null=True)),
                ('stock_yesterdayprice', models.CharField(max_length=10, null=True)),
                ('stock_startprice', models.CharField(max_length=10, null=True)),
                ('stock_gab', models.FloatField(null=True)),
                ('stock_gabwon', models.IntegerField(null=True)),
                ('stock_memo', models.TextField(null=True)),
                ('create_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
