# Generated by Django 3.0.3 on 2020-09-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stockitems', '0003_stock_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='stock_keypoint',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
